basic.showString("vou te ajudar a direcionar")
basic.pause(5000)
let sprite = game.createSprite(2, 4)
basic.pause(5000)
sprite = game.createSprite(2, 3)
basic.pause(5000)
sprite = game.createSprite(2, 2)
basic.pause(5000)
sprite = game.createSprite(2, 1)
basic.pause(5000)
sprite = game.createSprite(3, 1)
basic.pause(5000)
sprite = game.createSprite(4, 0)
sprite = game.createSprite(4, 1)
sprite = game.createSprite(4, 2)
sprite = game.createSprite(4, 3)
sprite = game.createSprite(4, 4)
basic.pause(5000)
game.gameOver()
