basic.show_string("v")
sprite = game.create_sprite(2, 4)
basic.pause(2000)
sprite = game.create_sprite(2, 3)
basic.pause(2000)
sprite = game.create_sprite(2, 2)
basic.pause(2000)
sprite = game.create_sprite(2, 1)
sprite.turn(Direction.RIGHT, 45)